---
galaxy_info:
  author: "Inverse inc <info@inverse.ca>"
  description: "Install and configure MailHog"
  company: "Inverse inc"
  license: "license (BSD, MIT)"  
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - stretch

  galaxy_tags:
    - development
    - web
    - system
    - mail
    - mailhog
