---
- name: Download and install Venom binary
  get_url:
    url: 'https://github.com/ovh/venom/releases/download/{{ venom__version }}/venom.{{ venom__os }}-{{ venom__arch }}'
    dest: "{{ venom__bin_path }}/venom"
    mode: '0755'
    force: yes
    owner: 'root'
    group: 'root'
  register: reg_install_venom
  retries: 5
  delay: 10
  until: reg_install_venom is succeeded
