---
# Debian install
- name: (Debian) install on Debian
  block:
    - name: Install wpa-supplicant
      apt:
        name: hostapd
        state: latest
        update_cache: '{{ hostapd__pkg_update_cache }}'
  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        msg: 'I caught an error'
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Redhat install
- name: (Redhat) Install on Redhat
  block:
    - name: Install wpa_supplicant
      yum:
        name: hostapd
        state: latest
        update_cache: '{{ hostapd__pkg_update_cache }}'
  rescue:
    - name: Print when errors
      ansible.builtin.debug:
        msg: 'I caught an error'
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
...
