---
# tasks file for hostapd
- name: Ensure wpasupplicant installed
  include_tasks: install.yml

- name: Configure hostapd for RADIUS
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd.conf
  notify: apply changes

- name: Start and enable hostapd service
  service:
    name: hostapd
    state: "{{ hostapd__state }}"
    enabled: "{{ hostapd__enabled }}"
