---
# hostapd services for wireless
- name: install hostapd service script
  template:
    src: hostapd.service.j2
    dest: '/etc/systemd/system/hostapd_{{ item }}.service'
    owner: root
    group: root
    mode: 0644
  loop:
    - open
    - secure

- name: reload systemctl
  systemd:
    daemon_reload: yes  

- name: Remove mask
  systemd:
    name: 'hostapd{{ item }}'
    enabled: yes
    masked:  no
    state: stopped
  loop:
    - ""
    - _open
    - _secure

# start a the default
- name: Start and enable hostapd default service
  service:
    name: hostapd
    state: started
    enabled: no
