---
- name: Download and install psonoci binary
  get_url:
    url: 'https://get.psono.com/psono/psono-ci/{{ psonoci__arch }}-{{ psonoci__os }}/psonoci'
    dest: "{{ psonoci__bin_path }}/psonoci"
    mode: '0755'
    force: yes    
    owner: 'root'
    group: 'root'
  register: reg_install_psonoci
  retries: 5
  delay: 10
  until: reg_install_psonoci is succeeded
