---
# Install and configure MailHog.
- name: Ensure mailhog install directory exists.
  file:
    path: "{{ mailhog__install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Download MailHog and mhsendmail binaries.
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - url: "{{ mailhog__binary_url }}"
      dest: "{{ mailhog__install_dir }}/mailhog"
    - url: "{{ mhsendmail__binary_url }}"
      dest: "{{ mailhog__install_dir }}/mhsendmail"
  register: reg_install_mailhog
  retries: 5
  delay: 10
  until: reg_install_mailhog is succeeded

- name: Copy mailhog systemd unit file into place
  template:
    src: mailhog.unit.j2
    dest: /etc/systemd/system/mailhog.service
    owner: root
    group: root
    mode: 0755
  register: mailhog_register_unit_file_installed

- name: Reload systemd daemons
  systemd:
    daemon_reload: True
  when: mailhog_register_unit_file_installed is changed

- name: Configure MailHog using environment variables
  template:
    src: mailhog.env
    dest: "{{ mailhog__env_file }}"
    owner: root
    group: root
    mode: 0600
  notify: Restart mailhog

- name: Ensure mailhog is enabled and will start on boot.
  service:
    name: mailhog
    state: started
    enabled: yes
